# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 10:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('participants', models.TextField()),
                ('min_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('skills', models.TextField()),
                ('tags', models.TextField()),
                ('hackathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Hackathon')),
            ],
        ),
    ]
