# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Hackathon'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
